# Generated by Django 5.2.14 on 2026-05-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izvodjac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('drzava', models.CharField(blank=True, max_length=50)),
                ('godina_osnivanja', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Izvodjac',
                'verbose_name_plural': 'Izvodjaci',
                'ordering': ['ime'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Zanr',
                'verbose_name_plural': 'Zanrovi',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('godina', models.IntegerField()),
                ('broj_pjesama', models.IntegerField()),
                ('trajanje_min', models.IntegerField(help_text='Ukupno trajanje u minutama')),
                ('omot', models.ImageField(blank=True, null=True, upload_to='omoti/')),
                ('opis', models.TextField(blank=True)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('izvodjac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumi', to='albumi.izvodjac')),
                ('zanr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumi', to='albumi.zanr')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumi',
                'ordering': ['-godina', 'naslov'],
            },
        ),
    ]
