# Generated by Django 5.2.14 on 2026-05-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodaje', to='albumi.album')),
                ('kupac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prodaja',
                'verbose_name_plural': 'Prodaje',
                'ordering': ['-datum'],
            },
        ),
    ]
