# Generated by Django 5.2.14 on 2026-05-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumi', '0002_prodaja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodaja',
        ),
    ]
