# Generated by Django 5.2.14 on 2026-06-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumi', '0004_album_cijena_prodaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodaja',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodaje', to='albumi.album'),
        ),
    ]
